// public api
export const apis = [
  {
    name: '获取 API 密钥',
    description: '获取当前登录态对应的 API 密钥(auth-key)。',
    url: '/api/public/v1/authkey',
    method: 'GET',
    params: [],
    responseSample: {
      code: 0,
      data: '4fe63159e8184c10a2fd93610bbf93d0',
    },
    remark: '需要先在当前站点完成扫码登录；该接口会校验真实 cookie 是否仍然有效。',
  },
  {
    name: '根据关键字搜索公众号',
    description: '根据公众号名称或关键字查询公众号列表。',
    url: '/api/public/v1/account',
    method: 'GET',
    params: [
      {
        label: '关键字',
        name: 'keyword',
        location: 'query',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '',
      },
      {
        label: '起始索引',
        name: 'begin',
        location: 'query',
        required: false,
        default: '0',
        type: 'Int',
        remark: '下标从0开始，不能为负',
      },
      {
        label: '返回条数',
        name: 'size',
        location: 'query',
        required: false,
        default: '5',
        type: 'Int',
        remark: '最大不得超过20',
      },
    ],
    responseSample: {
      base_resp: {
        ret: 0,
        err_msg: 'ok',
      },
      total: 2,
      list: [
        {
          fakeid: 'MzA3NzAyMzMyMA==',
          nickname: '铁路12306',
          alias: 'CRTT12306',
          round_head_img:
            'http://mmbiz.qpic.cn/mmbiz_png/1774PicJv1ocOBxUD1Kh8gqx6HmD105nGnCg4j84mw4gxtmgsbgaVbiaOq6fCgVpHjwjELnMTGV8IR6kq7XJNkdw/0?wx_fmt=png',
          service_type: 2,
          signature: '欢迎您关注铁路12306，我们竭诚为您提供火车票、畅行会员、列车餐饮、酒店预订、旅游等服务。',
          verify_status: 2,
        },
        {
          fakeid: 'MjM5NTM0Mzg0MA==',
          nickname: '12321受理中心',
          alias: 'zg12321jbzx',
          round_head_img:
            'http://mmbiz.qpic.cn/mmbiz_png/b6geF0mDiaH4E82KiagmLc2DiaPrvzbSaELEde0xfZXrmcUzdBjK2G0ME4U1rwCvk0ZmtUsOncAkpnYTNoyDfhx6A/0?wx_fmt=png',
          service_type: 2,
          signature: ' ',
          verify_status: 2,
        },
      ],
    },
    remark: '此接口不需要 API 密钥',
  },
  {
    name: '添加公众号到数据库',
    description: '保存公众号到数据库，兼容页面保存公众号时使用的字段结构。',
    url: '/api/public/v1/account',
    method: 'POST',
    params: [
      {
        label: '公众号id',
        name: 'fakeid',
        location: 'body',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '直接传单个对象时必填',
      },
      {
        label: '公众号名称',
        name: 'nickname',
        location: 'body',
        required: false,
        default: 'fakeid',
        type: 'String',
        remark: '与页面搜索结果字段一致',
      },
      {
        label: '对象类型',
        name: 'type',
        location: 'body',
        required: false,
        default: 'account',
        type: 'String',
        remark: '兼容页面搜索结果原样提交，服务端当前仅透传回响应',
      },
      {
        label: '微信号',
        name: 'alias',
        location: 'body',
        required: false,
        default: 'N/A',
        type: 'String',
        remark: '兼容页面搜索结果原样提交，服务端当前仅透传回响应',
      },
      {
        label: '头像链接',
        name: 'round_head_img',
        location: 'body',
        required: false,
        default: 'N/A',
        type: 'String',
        remark: '',
      },
      {
        label: '公众号类型',
        name: 'service_type',
        location: 'body',
        required: false,
        default: 'null',
        type: 'Int',
        remark: '1=订阅号，2=服务号',
      },
      {
        label: '公众号简介',
        name: 'signature',
        location: 'body',
        required: false,
        default: 'N/A',
        type: 'String',
        remark: '兼容页面搜索结果原样提交，服务端当前仅透传回响应',
      },
      {
        label: '是否半导体行业',
        name: 'is_semiconductor',
        location: 'body',
        required: false,
        default: '0',
        type: 'Int',
        remark: '0 否，1 是',
      },
      {
        label: '页面保存接口兼容数组',
        name: 'mpAccounts',
        location: 'body',
        required: false,
        default: 'N/A',
        type: 'Array<Object>',
        remark: '可直接提交页面保存公众号时的 mpAccounts 数组，数组元素字段与上方一致',
      },
    ],
    responseSample: {
      base_resp: {
        ret: 0,
        err_msg: 'ok',
      },
      account: {
        fakeid: 'MzA3NzAyMzMyMA==',
        nickname: '铁路12306',
        type: 'account',
        alias: 'CRTT12306',
        round_head_img:
          'http://mmbiz.qpic.cn/mmbiz_png/1774PicJv1ocOBxUD1Kh8gqx6HmD105nGnCg4j84mw4gxtmgsbgaVbiaOq6fCgVpHjwjELnMTGV8IR6kq7XJNkdw/0?wx_fmt=png',
        service_type: 2,
        signature: '欢迎您关注铁路12306，我们竭诚为您提供火车票、畅行会员等服务。',
        is_semiconductor: 0,
      },
      accounts: [
        {
          fakeid: 'MzA3NzAyMzMyMA==',
          nickname: '铁路12306',
          type: 'account',
          alias: 'CRTT12306',
          round_head_img:
            'http://mmbiz.qpic.cn/mmbiz_png/1774PicJv1ocOBxUD1Kh8gqx6HmD105nGnCg4j84mw4gxtmgsbgaVbiaOq6fCgVpHjwjELnMTGV8IR6kq7XJNkdw/0?wx_fmt=png',
          service_type: 2,
          signature: '欢迎您关注铁路12306，我们竭诚为您提供火车票、畅行会员等服务。',
          is_semiconductor: 0,
        },
      ],
    },
    remark: '此接口不需要 API 密钥；请求体兼容 raw body / account / mpAccount / mpAccounts 结构。',
  },
  {
    name: '根据文章链接搜索公众号',
    description: '根据公众号文章链接查询公众号。',
    url: '/api/public/v1/accountbyurl',
    method: 'GET',
    params: [
      {
        label: '文章链接',
        name: 'url',
        location: 'query',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '',
      },
    ],
    responseSample: {
      base_resp: {
        ret: 0,
        err_msg: 'ok',
      },
      list: [
        {
          fakeid: 'MzA3NTg4MDUzNQ==',
          nickname: '肖小跑',
          alias: '',
          round_head_img:
            'http://mmbiz.qpic.cn/mmbiz_png/TEq4bibSxYafowUFshRICokwNXiaUB9zCX3vicx8FuhTCGibTa478JI72bkbpa89ssAqEFm2ib1S1LB0FEjHycjib8OA/0?wx_fmt=png',
          service_type: 1,
          signature:
            '金融世界不讲道理的时候，向文史哲求救，大概率“叮”的一下就扣上了。因为在这里，您才能再次看到“人”：人的情绪，人的荒诞，人的大举动小动作。这里有世界最本质的规律。',
          verify_status: 0,
        },
      ],
      total: 1,
    },
  },
  {
    name: '获取文章列表',
    description: '获取公众号的历史文章列表',
    url: '/api/public/v1/article',
    method: 'GET',
    params: [
      {
        label: '公众号id',
        name: 'fakeid',
        location: 'query',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '',
      },
      {
        label: '起始索引',
        name: 'begin',
        location: 'query',
        required: false,
        default: '0',
        type: 'Int',
        remark: '下标从0开始，不能为负',
      },
      {
        label: '返回消息条数',
        name: 'size',
        location: 'query',
        required: false,
        default: '5',
        type: 'Int',
        remark: '最大不得超过20，一条消息可能会包含多篇文章',
      },
    ],
    responseSample: {
      base_resp: {
        err_msg: 'ok',
        ret: 0,
      },
      articles: [
        {
          aid: '2247503214_1',
          title: '我用ChatGPT AI Agent做了一个堆栈模拟器！',
          cover:
            'https://mmbiz.qpic.cn/mmbiz_jpg/jXQDbLkGBYXdb3LgmxYMRclBo2wibeyib4MFwhyI3mWQ6dwZOKvCXWibCXVLnr9e0rTUf9IzZn3LPDQBlEwXzyJ8Q/0?wx_fmt=jpeg',
          link: 'https://mp.weixin.qq.com/s/wZxawrdSdSUAAZc89XuhWg',
          digest: '',
          update_time: 1753666492,
          appmsgid: 2247503214,
          itemidx: 1,
          item_show_type: 0,
          author_name: '轩辕之风',
          tagid: [],
          create_time: 1753666493,
          is_pay_subscribe: 0,
          has_red_packet_cover: 0,
          album_id: '3457885223537541125',
          checking: 0,
          media_duration: '0:00',
          mediaapi_publish_status: 0,
          copyright_type: 1,
          appmsg_album_infos: [
            {
              id: '3457885223537541125',
              title: '人工智能',
              album_id: 3457885223537541000,
              appmsg_album_infos: [],
              tagSource: 0,
            },
          ],
          pay_album_info: {
            appmsg_album_infos: [],
          },
          is_deleted: false,
          ban_flag: 0,
          pic_cdn_url_235_1:
            'https://mmbiz.qpic.cn/mmbiz_jpg/jXQDbLkGBYXdb3LgmxYMRclBo2wibeyib4V7nwzMbwLYKbgFSSbnQt0rUmdz1XcSE33YFzfqpVrYNKD8DagbnPRw/0?wx_fmt=jpeg',
          pic_cdn_url_16_9: '',
          pic_cdn_url_3_4: '',
          pic_cdn_url_1_1:
            'https://mmbiz.qpic.cn/mmbiz_jpg/jXQDbLkGBYXdb3LgmxYMRclBo2wibeyib4MFwhyI3mWQ6dwZOKvCXWibCXVLnr9e0rTUf9IzZn3LPDQBlEwXzyJ8Q/0?wx_fmt=jpeg',
          cover_img:
            'http://mmbiz.qpic.cn/mmbiz_jpg/jXQDbLkGBYXdb3LgmxYMRclBo2wibeyib4MFwhyI3mWQ6dwZOKvCXWibCXVLnr9e0rTUf9IzZn3LPDQBlEwXzyJ8Q/0?wx_fmt=jpeg',
          cover_img_theme_color: {
            r: 255,
            g: 255,
            b: 255,
          },
          line_info: {
            use_line: 1,
            line_count: 0,
            is_appmsg_flag: 1,
            is_use_flag: 0,
          },
          copyright_stat: 1,
          is_rumor_refutation: 0,
          multi_picture_cover: 0,
          share_imageinfo: [],
        },
        {
          aid: '2247503179_1',
          title: '抖音C++安全开发面试题，已阵亡！',
          cover:
            'https://mmbiz.qpic.cn/mmbiz_jpg/jXQDbLkGBYUYIgV3fNdQyKIysEER6tQZCpgfTrYwfKX67eRWicg9TIciadwXJF9QMhUiaLaR4iabdwdiaib7FmWY62eg/0?wx_fmt=jpeg',
          link: 'https://mp.weixin.qq.com/s/eFsIOWDXfs9DbcNmr2vtjQ',
          digest: '',
          update_time: 1753230604,
          appmsgid: 2247503179,
          itemidx: 1,
          item_show_type: 0,
          author_name: '轩辕之风',
          tagid: [],
          create_time: 1753230605,
          is_pay_subscribe: 0,
          has_red_packet_cover: 0,
          album_id: '3560766261049098241',
          checking: 0,
          media_duration: '0:00',
          mediaapi_publish_status: 0,
          copyright_type: 1,
          appmsg_album_infos: [
            {
              id: '3560766261049098241',
              title: 'C/C++',
              album_id: 3560766261049098000,
              appmsg_album_infos: [],
              tagSource: 0,
            },
          ],
          pay_album_info: {
            appmsg_album_infos: [],
          },
          is_deleted: false,
          ban_flag: 0,
          pic_cdn_url_235_1:
            'https://mmbiz.qpic.cn/mmbiz_jpg/jXQDbLkGBYUYIgV3fNdQyKIysEER6tQZuuUaqiazzPPoUFqFWicZ7bsW8z6g9FhkbibyqRtfZwRAkFHhPIydWpLnQ/0?wx_fmt=jpeg',
          pic_cdn_url_16_9: '',
          pic_cdn_url_3_4: '',
          pic_cdn_url_1_1:
            'https://mmbiz.qpic.cn/mmbiz_jpg/jXQDbLkGBYUYIgV3fNdQyKIysEER6tQZCpgfTrYwfKX67eRWicg9TIciadwXJF9QMhUiaLaR4iabdwdiaib7FmWY62eg/0?wx_fmt=jpeg',
          line_info: {
            use_line: 1,
            line_count: 0,
            is_appmsg_flag: 1,
            is_use_flag: 0,
          },
          copyright_stat: 1,
          is_rumor_refutation: 0,
          multi_picture_cover: 0,
          share_imageinfo: [],
        },
      ],
    },
  },
  {
    name: '获取文章内容',
    description: '获取文章内容，支持 html / markdown / text / json 格式',
    url: '/api/public/v1/download',
    method: 'GET',
    params: [
      {
        label: '文章链接',
        name: 'url',
        location: 'query',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '需经过url编码',
      },
      {
        label: '输出格式',
        name: 'format',
        location: 'query',
        required: false,
        default: 'html',
        type: 'String',
        remark: '支持 html / markdown / text / json 格式',
      },
    ],
    responseSample: {},
    remark: '此接口不需要 API 密钥',
  },
  {
    name: '获取数据库中的公众号列表',
    description: '返回数据库中已经保存过的公众号基础信息。',
    url: '/api/public/v1/db/accounts',
    method: 'GET',
    params: [],
    responseSample: {
      base_resp: {
        ret: 0,
        err_msg: 'ok',
      },
      total: 1,
      list: [
        {
          fakeid: 'MzA3NzAyMzMyMA==',
          nickname: '铁路12306',
          round_head_img:
            'http://mmbiz.qpic.cn/mmbiz_png/1774PicJv1ocOBxUD1Kh8gqx6HmD105nGnCg4j84mw4gxtmgsbgaVbiaOq6fCgVpHjwjELnMTGV8IR6kq7XJNkdw/0?wx_fmt=png',
          service_type: 2,
          is_semiconductor: 0,
        },
      ],
    },
    remark: '此接口不需要 API 密钥。',
  },
  {
    name: '获取数据库文章列表',
    description: '根据一个或多个 fakeid 查询数据库中已保存的文章，支持按 update_time 时间范围过滤并分页返回。',
    url: '/api/public/v1/db/articles',
    method: 'POST',
    params: [
      {
        label: '公众号id数组',
        name: 'fakeids',
        location: 'body',
        required: true,
        default: '[]',
        type: 'Array<String>',
        remark: '至少传一个 fakeid；也兼容单个 fakeid 字符串字段',
      },
      {
        label: '页码',
        name: 'page',
        location: 'body',
        required: false,
        default: '1',
        type: 'Int',
        remark: '从1开始',
      },
      {
        label: '每页条数',
        name: 'size',
        location: 'body',
        required: false,
        default: '20',
        type: 'Int',
        remark: '默认20，最大100',
      },
      {
        label: '起始时间',
        name: 'start_time',
        location: 'body',
        required: false,
        default: 'N/A',
        type: 'Int',
        remark: '按 update_time 过滤，Unix 时间戳（秒），大于等于',
      },
      {
        label: '结束时间',
        name: 'end_time',
        location: 'body',
        required: false,
        default: 'N/A',
        type: 'Int',
        remark: '按 update_time 过滤，Unix 时间戳（秒），小于等于',
      },
    ],
    responseSample: {
      base_resp: {
        ret: 0,
        err_msg: 'ok',
      },
      filters: {
        start_time: 1753600000,
        end_time: 1753699999,
      },
      list: [
        {
          fakeid: 'MzA3NzAyMzMyMA==',
          update_time: 1753666492,
          article_title: '我用ChatGPT AI Agent做了一个堆栈模拟器！',
          link: 'https://mp.weixin.qq.com/s/wZxawrdSdSUAAZc89XuhWg',
          cover: 'https://mmbiz.qpic.cn/sz_mmbiz_jpg/example/640?wx_fmt=jpeg',
          digest: '用 AI Agent 做一个可交互的堆栈模拟器。',
          is_deleted: false,
        },
      ],
      pagination: {
        page: 1,
        size: 20,
        total: 1,
        total_pages: 1,
        has_next: false,
        has_prev: false,
      },
    },
    remark: '此接口不需要 API 密钥。',
  },
  {
    name: '按链接获取文章内容',
    description: '根据文章链接获取内容，参数与页面展示一致，支持 html / markdown / text / json。',
    url: '/api/public/v1/db/content',
    method: 'GET',
    params: [
      {
        label: '文章链接',
        name: 'url',
        location: 'query',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '需经过url编码',
      },
      {
        label: '输出格式',
        name: 'format',
        location: 'query',
        required: false,
        default: 'html',
        type: 'String',
        remark: '支持 html / markdown / text / json 格式',
      },
    ],
    responseSample: {},
    remark: '此接口不需要 API 密钥；会优先命中已缓存内容，不足时再走抓取逻辑。',
  },
  {
    name: '查询公众号主体信息 (beta)',
    description: '根据公众号的 fakeid 查询主体信息',
    url: '/api/public/beta/authorinfo',
    method: 'GET',
    params: [
      {
        label: '公众号id',
        name: 'fakeid',
        location: 'query',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '',
      },
    ],
    responseSample: {
      base_resp: {
        exportkey_token: '',
        ret: 0,
      },
      identity_name: '上海市总工会',
      is_verify: 2,
      original_article_count: 262,
    },
    remark: '此接口不需要 API 密钥',
  },
  {
    name: '查询公众号主体信息 (beta)',
    description: '根据公众号的 fakeid 查询主体信息',
    url: '/api/public/beta/aboutbiz',
    method: 'GET',
    params: [
      {
        label: '公众号id',
        name: 'fakeid',
        location: 'query',
        required: true,
        default: 'N/A',
        type: 'String',
        remark: '',
      },
      {
        label: '密钥',
        name: 'key',
        location: 'query',
        required: false,
        default: 'N/A',
        type: 'String',
        remark: '微信抓包获取的x-wechat-key参数',
      },
    ],
    responseSample: {
      base_resp: {
        ret: 0,
      },
      data: {
        intro: '做一个有存在意义的账号~这里是上海市总工会，欢迎回家！',
        wechat: 'shengongshewx',
        type: '其他组织',
        org: '上海市总工会',
        auth_3rd_list: [
          {
            principal: '秀米',
            userName: 'gh_d483129a0f29@app',
            appId: 'wx19e904724550a41f',
            relativeURL:
              'pages/profile/index?enterpriseOpenId=sq_o0CFMs_h0aKah0GsYaZZ3akyF8yo&amp;from=profile&amp;fromAppId=wx63d70210fcc108fd&amp;componentAppId=wx7d88eb47efa1e610',
            category: [
              {
                id: 7,
                name: '群发与通知',
                desc: '基于该权限可帮助公众号进行群发消息、文章管理以及发送模板消息',
              },
              {
                id: 11,
                name: '素材管理',
                desc: '基于该权限可帮助公众号管理图文等多媒体素材以及多媒体文件管理',
              },
            ],
          },
          {
            principal: '壹伴',
            userName: 'gh_d483129a0f29@app',
            appId: 'wx19e904724550a41f',
            relativeURL:
              'pages/profile/index?enterpriseOpenId=sq_omefmt3a0XFwUA1PfscJj7_n9fak&amp;from=profile&amp;fromAppId=wx63d70210fcc108fd&amp;componentAppId=wx3f5f5ddf688562c0',
            category: [
              {
                id: 1,
                name: '消息管理',
                desc: '基于该权限可帮助公众号接收用户消息，进行人工客服回复或自动回复',
              },
              {
                id: 2,
                name: '用户管理',
                desc: '帮助公众号获取用户信息，进行用户管理',
              },
              {
                id: 3,
                name: '公众号账号信息服务',
                desc: '基于该权限可帮助公众号设置及展示公众号信息、配置账号信息、生成带参二维码并配置跳转小程序等账号维度的功能',
              },
              {
                id: 4,
                name: '网页服务',
                desc: '基于该权限可帮助公众实现H5网页服务',
              },
              {
                id: 6,
                name: '微信多客服',
                desc: '基于该权限可帮助公众号使用微信多客服功能',
              },
              {
                id: 7,
                name: '群发与通知',
                desc: '基于该权限可帮助公众号进行群发消息、文章管理以及发送模板消息',
              },
              {
                id: 11,
                name: '素材管理',
                desc: '基于该权限可帮助公众号管理图文等多媒体素材以及多媒体文件管理',
              },
              {
                id: 15,
                name: '自定义菜单管理',
                desc: '帮助公众号使用自定义菜单',
              },
            ],
          },
        ],
        ip_wording: {
          countryName: '中国',
          countryId: '156',
          provinceName: '上海',
          provinceId: '',
          cityName: '',
          cityId: '',
        },
      },
    },
    remark: '此接口不需要 API 密钥',
  },
];
